### ISSUE TITLE
Php 8.0 support

### ISSUE THREAD

**Issue by psntr** [bnomei/kirby3-lapse#23]
Hey me again!

Thank you for updating the boost plugin the other day.

I'm using the boost plugin with Lapse and now I'm facing the issue of platform requirement from the Lapse plugin.
```
Root composer.json requires bnomei/kirby3-lapse ^3.0 -> satisfiable by bnomei/kirby3-lapse[3.0.0, 3.1.0].
    - bnomei/kirby3-lapse[3.0.0, ..., 3.1.0] require php >=8.1.0 -> your php version (8.0.25)
```
Any advice would be appreciated!

**Comment by bnomei** [comment]
fixed by now
