### ISSUE TITLE
Can you explain how to use Lapse for partly page caching

### ISSUE THREAD

**Issue by alkachur** [bnomei/kirby3-lapse#9]
Hi there, 
As I understand this plugin is multifunctional and useful for many tasks.
I have problem with my site. 
I have many GeoIP dependent parts that is changed based on IP (geo) from what user visit site.
The best way is to cache all pages with country as a key, so, for example, I will have a page 
news.hungary.cache
news.netherlands.cache 
that will have different content 

or if this isn't possible explain how for example I can create cache for header and footer (that is similar for all countries).
also, I'm using builder plugin and every block also has Geo dependency, so if it possible to cache it depending on country.

Thanks, for help :) and trust that impossible possible)

**Comment by bnomei** [comment]
just put the name of the country inside the key (or key array).


```php
$country = getCountryNameFromIP($ip);  // you need to figure that part out, can not help you there
$data = Lapse::io(['news-cache-for', $country], function () use ($country) {
        $request = Remote::get('https://api.example.com/country/' . $country); // some api, just an example

        if ($request->code() === 200) {
            $results = $request->json(false)->data; // assuming a json like { data: [...] }
         }
         return $results ;
});

```
